### ISSUE TITLE
How to get list of issuers?

### ISSUE THREAD

**Issue by Lefthandmedia** [buckaroo-it/BuckarooSDK_PHP#100]
Is there a way to get a complete list of Ideal issuers?

**Comment by vegimcarkaxhija** [comment]
Dear @Lefthandmedia,

To get a complete list of Ideal issuers, you can use the following method in the code:

[#L26](https://github.com/buckaroo-it/BuckarooSDK_PHP/blob/master/example/transactions/ideal.php#L26)

If you need further assistance or clarification, feel free to ask.
