### ISSUE TITLE
[BP-1996] vlucas/phpdotenv should be dev-dependency

### ISSUE THREAD

**Issue by ederuiter** [buckaroo-it/BuckarooSDK_PHP#32]
Currently the `vlucas/phpdotenv` package is a direct dependency although it is only used in the examples/tests.

For us this lead to problems with an old laravel install (as laravel 7 required phpdotenv 4, and this package requires phpdotenv 5)

**Comment by ShuCh3n** [comment]
You're right! We are going to remove that

**Comment by Buckaroo-Rens** [comment]
Thanks again @ederuiter added the bug to one of our upcoming sprint. Are you helped with us providing a commit/patch in the meantime or can you wait until our next release?

**Comment by ederuiter** [comment]
I can wait until the next release as I was able to workaround it by adding this to our composer.json

```
"provide": {
        "vlucas/phpdotenv": "5.4"
    },
```

**Comment by Buckaroo-Rens** [comment]
Thanks @ederuiter, we keep you posted :)

**Comment by ShuCh3n** [comment]
vlucas/phpdotenv is moved to dev in the next update
