### ISSUE TITLE
BP-2018 Add a call to obtain the transaction status

### ISSUE THREAD

**Issue by antonboutkam** [buckaroo-it/BuckarooSDK_PHP#37]
What i actually also need is a mechanism to check on demand what the current status of my payment is. If there was some disruptance in a service somewhere along the way i need the system to be able to get all the statusses back on track.

**Comment by ShuCh3n** [comment]
We will add this to the sdk

**Comment by ShuCh3n** [comment]
We have added this functionality to the upcoming release.
