### ISSUE TITLE
The AfterPay example is not working

### ISSUE THREAD

**Issue by jurrienpiris** [buckaroo-it/BuckarooSDK_PHP#45]
### Introduction
The current example of [Afterpay](https://github.com/buckaroo-it/BuckarooSDK_PHP/blob/master/example/transactions/afterpay.php) is incorrect or incomplete. This results in the following errors:
```
- Parameter "VatPercentage" missing
- Parameter "GrossUnitPrice" missing
- Parameter "Description" missing
```

Unfortunately, adding these parameters does not solve this problem

### Environment
- Exacte copy of the [Afterpay](https://github.com/buckaroo-it/BuckarooSDK_PHP/blob/master/example/transactions/afterpay.php) example.
- Valid Buckaroo account with AfterPay activated.
- PHP 7.4

**Comment by serpentscode** [comment]
Hi @jurrienpiris, thanks for reporting this issue. The examples seem to be outdated, we'll update them on next release. 
Meanwhile try to use the payload from the test file.

https://github.com/buckaroo-it/BuckarooSDK_PHP/blob/4c66a6c19dea5e67f9977f03fa626e3c84dd07d4/src/Tests/Payments/AfterpayTest.php#L119-L183

**Comment by Skebantje** [comment]
Thanks for this working example. Could you please also tell me whats the correct way to set the Shipping Cost? I get error message: AmountDoesNotMatch: Pay rejected. The following errors occurred:(order.totalGrossAmount). This is because of the shipping costs.

**Comment by Skebantje** [comment]
Thank you very much! I have it all worked right now. I have only 1 issue left. When we use a discount code we get the error 'AmountDoesNotMatch: Pay rejected.'. What is the right way to use a discount code? It would be almost the same as the ShippingFee. I hope you can provide me an example.

**Comment by serpentscode** [comment]
Hi there, for adding a discount or additional fee you can add it as an article in the payload. Don't forget to adjust 'amountDebit' aswell to match the articles total amount.

Here's an example
```php
$response = $buckaroo->method('afterpay')->pay([
    'amountDebit'       => 40.30,
    'order'             => uniqid(),
    'invoice'           => uniqid(),
    'clientIP'      => '127.0.0.1',
    'billing'       => [
        'recipient'        => [
            'category'      => RecipientCategory::PERSON,
            'careOf'        => 'John Smith',
            'title'            => 'Mrs',
            'firstName'      => 'John',
            'lastName'      => 'Do',
            'birthDate'     => '1990-01-01',
            'conversationLanguage'  => 'NL',
            'identificationNumber'  => 'IdNumber12345',
            'customerNumber'        => 'customerNumber12345'
        ],
        'address'       => [
            'street'                => 'Hoofdstraat',
            'houseNumber'           => '13',
            'houseNumberAdditional' => 'a',
            'zipcode'               => '1234AB',
            'city'                  => 'Heerenveen',
            'country'               => 'NL'
        ],
        'phone'         => [
            'mobile'        => '0698765433',
            'landline'      => '0109876543'
        ],
        'email'         => 'test@buckaroo.nl'
    ],
    'shipping'      => [
        'recipient'        => [
            'category'      => RecipientCategory::COMPANY,
            'careOf'        => 'John Smith',
            'companyName'   => 'Buckaroo B.V.',
            'firstName'      => 'John',
            'lastName'          => 'Do',
            'chamberOfCommerce' => '12345678'
        ],
        'address'       => [
            'street'                => 'Kalverstraat',
            'houseNumber'           => '13',
            'houseNumberAdditional' => 'b',
            'zipcode'               => '4321EB',
            'city'                  => 'Amsterdam',
            'country'               => 'NL'
        ],
    ],
    'articles'      => [
        [
            'identifier' => 'Articlenumber1',
            'description' => 'Blue Toy Car',
            'vatPercentage' => '21',
            'quantity' => '2',
            'price' => '20.10'
        ],
        [
            'identifier' => 'Articlenumber2',
            'description' => 'Red Toy Car',
            'vatPercentage' => '21',
            'quantity' => '1',
            'price' => '10.10'
        ],
        [
            'identifier' => 'Discount',
            'description' => 'Discount Amount',
            'vatPercentage' => 0,
            'quantity' => '1',
            'price' => '-10'
        ]
    ]
]);
```

**Comment by Skebantje** [comment]
Thank you! I got it all worked right now!

**Comment by Buckaroo-Rene** [comment]
@Skebantje ,

Thank you for the confirmation. Good to hear that it is all working now 👍🏻 .
We'll close this issue .
