### ISSUE TITLE
Using ContinueOnIncomplete - iDeal without issuer

### ISSUE THREAD

**Issue by LoekJanssen** [buckaroo-it/BuckarooSDK_PHP#57]
According to the documentation I should be able to use "ContinueOnIncomplete", I can't get it to work with this SDK.

I don't want to set "issuer" when using iDeal as payment method. With "ContinueOnIncomplete" set, the user can choose the preferred bank in Buckaroo.

$response = $buckaroo->method('ideal')->pay([
                            'amountDebit'   => 10,
                            'invoice'       => uniqid(),
                            **'continueOnIncomplete' => 1**
             ]);

Documentation:
![image](https://user-images.githubusercontent.com/5222425/208099577-fa31e484-d701-4664-a685-73f3ab08485e.png)

**Comment by ShuCh3n** [comment]
Hi LoekJanssen,

Try this

```php
$buckaroo->method('ideal')->pay([
            'invoice' => 'INVOICENUMBER',
            'amountDebit' => 10.10,
            // 'issuer' => 'ABNANL2A',
            'continueOnIncomplete' => 1,
            'pushURL'  => 'https://buckaroo.nextto.dev/push',
            'returnURL' => 'https://buckaroo.nextto.dev/return'
        ]);
```

Remove the issuer completely and add continueOnIncomplete and set it to 1

**Comment by LoekJanssen** [comment]
Thank you for the response. I tried your solution and I'm getting the message "Parameter 'issuer' missing" (from $response->getSomeError() )

**Comment by ShuCh3n** [comment]
Can you copy your code?

**Comment by LoekJanssen** [comment]
The $response->hasSomeError() gives me an error.
$response->hasRedirect() gives me no URL.
I'm using V1.1.2

```
$response = $buckaroo->method('ideal')
            ->pay([
                'amountDebit'   => 10,
                'invoice'       => uniqid(),
                'ContinueOnIncomplete' => 1
            ]);
        
        if($response->hasSomeError()){
            $error = $response->getSomeError();
            // Problem: This error shows message "Parameter 'issuer' missing"
        }
        
        if($response->hasRedirect()){
            $redirectUrl = $response->getRedirectUrl();
           // Problem: There is no redirectURL available
        }
```

**Comment by ShuCh3n** [comment]
Can you try using v1.2

**Comment by LoekJanssen** [comment]
I'm not getting a different result in V1.2.0

**Comment by LoekJanssen** [comment]
That was the problem.. sorry for not using the latest version.. Thank you for looking at the problem!
Apparently Composer didn't load that version with "composer require buckaroo/sdk:^1.0" command.

**Comment by Buckaroo-Rene** [comment]
@LoekJanssen ,

No problem and good to hear that it is now working with the latest version.
We'll close this issue.
