### ISSUE TITLE
Example 'no primary service' missing

### ISSUE THREAD

**Issue by LoekJanssen** [buckaroo-it/BuckarooSDK_PHP#58]
I can't find an example for sending a transaction request without using a primary Service.
In the screenshot below "If no primary service is provided and ContinueOnIncomplete is set" indicates that I don't need a primary Service.
All examples have a method. (for example $buckaroo->method('afterpay') - I would like to not send "afterpay" and let the customer choose in Buckaroo)

https://docs.buckaroo.io/docs/en/parameters

![image](https://user-images.githubusercontent.com/5222425/208663947-f6461817-2a32-4f70-ab1a-d847b57e3bce.png)

**Comment by ShuCh3n** [comment]
In your example, "Afterpay", there is no hosted page for this payment method. For afterpay we are required to have more information about the order. Like the products, prices, VAT, shipping/billing information etc.

But I understand your point. Currently, this function is not supported by the SDK. We could implement this feature in the future. But never the less, this still won't work for some payment methods such as afterpay, klarna...

Is there any particular reason you want to work like this? Maybe we can give you some advice.

**Comment by LoekJanssen** [comment]
Thanks you for the fast response.
I don't mind sending to much data to Buckaroo. I would like to send the customer to Buckaroo and let the customer choose the payment service. (for example: Afterpay, in3, iDeal, Paypal) Based on the data I send, Buckaroo can show the available services.

**Comment by ShuCh3n** [comment]
Thanks for the explanation. Unfortunately, this ServicesSelectableByClient function won't work for the more complex payment methods (eg. Afterpay, In3, Klarna etc.) 

So even if you send all the required information for an unknown payment method, this still won't work within our workflow. I suggest you create your own payment page to let the user choose the payment method upfront and, based on that, send the payload to Buckaroo by using the SDK. 

I hope this could help you.
