### ISSUE TITLE
Unit test naming contradicts assertion

### ISSUE THREAD

**Issue by avido** [buckaroo-it/BuckarooSDK_PHP#62]
test: `it_creates_a_combined_subscription()` found in `src/Tests/Payments/SubscriptionsTest.php` suggest a successful created subscription.. However an assertion on validationFailure is done. 
```php
        $this->assertTrue($response->isValidationFailure());
``` 
The test above fails with validation error: `Action 'CreateCombinedSubscription' on transaction requests only possible with basic parameter 'StartRecurrent' set to true"`

**Comment by ShuCh3n** [comment]
Dear Avido,

Yes, we know some tests pass the unit test even if there is a validation failure. Thank you for mentioning it! Can you show me the entire payload you are trying to send?

**Comment by avido** [comment]
HI,

I use the test as it is with exception of the configuration values.

```php
        $subscriptions = $this->buckaroo->method('subscriptions')->manually()->createCombined([
            'includeTransaction'        => false,
            'transactionVatPercentage'  => 5,
            'configurationCode'         => 'qssjq32w',
            'email'                     => 'test@buckaroo.nl',
            'rate_plans'        => [
                'add'        => [
                    'startDate'         => '2023-01-01',
                    'ratePlanCode'      => '58mknguz',
                ]
            ],
            'phone'                     => [
                'mobile'                => '0612345678'
            ],
            'debtor'                    => [
                'code'          => '11840'
            ],
            'person'                    => [
                'firstName'         => 'John',
                'lastName'          => 'Do',
                'gender'            => Gender::FEMALE,
                'culture'           => 'nl-NL',
                'birthDate'         => '1990-01-01'
            ],
            'address'           => [
                'street'        => 'Hoofdstraat',
                'houseNumber'   => '90',
                'zipcode'       => '8441ER',
                'city'          => 'Heerenveen',
                'country'       => 'NL'
            ]
        ]);
```

**Comment by ShuCh3n** [comment]
Dear @avido 

Thank you for bringing this to our attention.

We have fixed the issue.

https://github.com/buckaroo-it/BuckarooSDK_PHP/pull/63/files

**Comment by avido** [comment]
Hi @ShuCh3n, i can confirm the change. 

However i think it's wise to review the other tests as well as they seem to have the same problem. 
Also i would use the current Year+1 as `startDate` as a fixed date isn't sustainable

**Comment by Buckaroo-Rens** [comment]
@avido Thank you for your confirmation. It was indeed our plan to re-evaluate all the tests. Thanks again for the input :)

**Comment by avido** [comment]
@Buckaroo-Rens Do you have an estimate ? We are currently implementing the SDK in our Project but it's cumbersome as the documentation is incomplete and we try to rely on the unit tests

**Comment by Buckaroo-Rens** [comment]
This month for sure, but if you have anything missing/failing right now, please let us know so we can help you right away. The SKD is still new so we are also trying to figure out were extra documentation is helpfull.

**Comment by avido** [comment]
Will do ! 

for now it would be nice if the unit test are up2date and if needed documented. The current documentation found at buckaroo lacks of specification (type of arguments, length limitation etc). Also we have the feeling not every argument is documented online.

**Comment by Buckaroo-Rens** [comment]
You are completely right! I'm guessing you mean docs.buckaroo.nl which is our new documentation environment. Especially for the PHP SDK there is little to nothing to be found there. Thanks again for your input. More than welcome :)
