### ISSUE TITLE
Transaction `status()` return type

### ISSUE THREAD

**Issue by avido** [buckaroo-it/BuckarooSDK_PHP#71]
Currently the `Buckaroo\Services\TransactionService\status()` returns `Buckaroo\Transaction\Response\Response` 
shouldn't this be `TransactionResponse` ? As `Respone` is returned, nifty methods such as `isSuccess` aren't available.

**Comment by ShuCh3n** [comment]
That's actually a great point, I will update that.

**Comment by ShuCh3n** [comment]
There is PR for this change #73
