### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by avido** [buckaroo-it/BuckarooSDK_PHP#72]
Hi, 

When is the next release expected? 
Is there an overview of release cycles?

**Comment by ShuCh3n** [comment]
Dear @avido 

We are currently preparing for the next release. Most likely, it will be somewhere in the upcoming week. Is there anything particular feature you are waiting for? Or are you currently using the dev branch?

**Comment by avido** [comment]
saw some changes in the dev branch (for example ideal issuers). and since the last release is nov i expected / hoped for a new release soon :)

**Comment by ShuCh3n** [comment]
Alright! We will do our best to release it next week.

**Comment by Buckaroo-Rens** [comment]
Release 1.3.0 is done @avido
