### ISSUE TITLE
Issue with using 'pushURL' and 'additionalParameters' parameters

### ISSUE THREAD

**Issue by reflie-nxte** [buckaroo-it/BuckarooSDK_PHP#75]
Hello.

During creating an encrypted payment I'm trying to do two things: to override default push url and to pass some additional custom parameters (which I expect to receive on my endpoint).

Here is the code I'm using:

>     $response = $this->api->method('creditcard')->payEncrypted([
>       'currency' => 'EUR',
>       'amountDebit' => '10.00',
>       'invoice' => 'INV-0012345',
>       'name' => 'mastercard',
>       'encryptedCardData' => $credit_card,
>       'returnURL' => 'https://mysite.loc/order/0012345',
>       'pushURL' => 'https://mysite.loc/json/buckaroo',
>       'additionalParameters' => [
>         'Name' => 'paymentGateway',
>         'Value' => 'mastercard_buckaroo',
>       ],
>     ]);

The problem is that 'pushURL' and 'additionalParameters' parameters doesn't work. However, the similar to 'pushURL' parameter 'returnURL' one works as expected. This is strange.

As specified in documentation, PushURL "overrides all the push URLs as configured in the payment plaza under websites for the associated website key" but this doesn't happen. I'm receiving all the time the request to the URL specified in Plaza.

Could you please clarify this?

Thank you!

**Comment by ShuCh3n** [comment]
Dear @reflie-nxte 

Try the additionalParameters like this 

```php
$response = $this->api->method('creditcard')->payEncrypted([
  'currency' => 'EUR',
  'amountDebit' => '10.00',
  'invoice' => 'INV-0012345',
  'name' => 'mastercard',
  'encryptedCardData' => $credit_card,
  'returnURL' => 'https://mysite.loc/order/0012345',
  'pushURL' => 'https://mysite.loc/json/buckaroo',
  'additionalParameters' => [
    'paymentGateway' => 'mastercard_buckaroo'
  ],
]);
```

The push URL should be working like this. Can you check the transaction in Plaza if there is any call made to the push URL?

Also, it's a local URL so our server won't reach your destination. (https://mysite.loc/json/buckaroo)

**Comment by reflie-nxte** [comment]
Dead @ShuCh3n.

Thank you for quick reply. I tried mentioned syntax for 'additionalParameters' but it doesn't work. 

The 'push URL' doesn't work too. It doesn't matter which URL I provide there. All the time it does send push data to the one specified in Plaza. But there is one interesting thing: if I provide it like this: 'pushURL' - I do not receive reply at all. However, using next syntax: 'PushURL' I receive reply on the URL specified in Plaza, not provided with this parameter.

Here is which data I receive on the endpoint specified in Plaza after successful credit card transaction:

![image](https://user-images.githubusercontent.com/122365318/215357778-99913ee8-d925-4891-b4e1-1ddd9d744651.png)

As you can see, there is are no 'AdditionalParameters'. However, in the post request I provided both: 'PushURL' and 'AdditionalParameters', but they didn't work.


> Also, it's a local URL so our server won't reach your destination. (https://mysite.loc/json/buckaroo)
This was just an example. Could you please check if these parameters works for you? This looks like some global issue.

Maybe there are some additional settings in the Plaza that can affect this functionality?

**Comment by ShuCh3n** [comment]
We just release [ v1.3.0](https://github.com/buckaroo-it/BuckarooSDK_PHP/releases/tag/1.3.0) you can updated from composer

**Comment by reflie-nxte** [comment]
Great. Thank you. I will try it and I will let you know about results.

**Comment by reflie-nxte** [comment]
Hi @ShuCh3n. All works as expected. PushIRL didn't work initially because it requires having local machine available from the web. I tried to use it thru [ngrock](https://ngrok.com/) and it started working as expected.
