### ISSUE TITLE
BP-2347 Add default Stdout Logger

### ISSUE THREAD

**Issue by 123lens** [buckaroo-it/BuckarooSDK_PHP#82]
Is there a clear reason for logging al requests to stdOut ?

I'd like to debate the default behaviour to be none.

**Comment by ShuCh3n** [comment]
Dear 123lens,

That's a great suggestion. We will add a debug level.

**Comment by avido** [comment]
?

**Comment by ShuCh3n** [comment]
#163 PR has been created
