### ISSUE TITLE
BP-2351 TransactionResponse::getSubStatusCode() returns string

### ISSUE THREAD

**Issue by tombroucke** [buckaroo-it/BuckarooSDK_PHP#87]
Typehinting for the TransactionResponse::getSubStatusCode() method states that the method should return an integer or null, but in my response, `$this->data['Status']['SubCode']['Code']` is a string (`S990`). This is causing a fatal error on PHP 8.

PHP Fatal error:  Uncaught TypeError: Return value of Buckaroo\Transaction\Response\TransactionResponse::getSubStatusCode() must be of the type int or null, string returned in `vendor/buckaroo/sdk/src/Transaction/Response/TransactionResponse.php:295`

**Comment by ShuCh3n** [comment]
Dear @tombroucke 

Thanks for mentioning the issue. I will look into it.

**Comment by ShuCh3n** [comment]
Fixed #88
