### ISSUE TITLE
 Uncaught Error: Class "Buckaroo" not found 

### ISSUE THREAD

**Issue by abrookbanks** [buckaroo-it/BuckarooSDK_PHP#89]
Is there a bug? If I create a comoser.json file and then build the library using composer the main class object isn't found.

public_html/composer.json
```
{
    "require": {
        "buckaroo/sdk": "^1.0"
    }
}
```

`composer install`

public_html/index.php
```
<?php
require __DIR__ . '/vendor/autoload.php';

# Get your website & secret key in your plaza.
$buckaroo = new \Buckaroo('xxx', 'yyy');
```

**Comment by avido** [comment]
> Is there a bug? If I create a comoser.json file and then build the library using composer the main class object isn't found.
> 
> public_html/composer.json
> 
> ```
> {
>     "require": {
>         "buckaroo/sdk": "^1.0"
>     }
> }
> ```
> 
> `composer install`
> 
> public_html/index.php
> 
> ```
> <?php
> require __DIR__ . '/vendor/autoload.php';
> 
> # Get your website & secret key in your plaza.
> $buckaroo = new \Buckaroo('xxx', 'yyy');
> ```

Buckaroo is the namespace..
Try 
```php
$client = new Buckaroo\BuckarooClient('xxx', 'yyy');
```

**Comment by abrookbanks** [comment]
Thanks I think this worked. Your documentation is wrong: 

https://docs.buckaroo.io/docs/php-sdk 

> require __DIR__ . '/vendor/autoload.php';
>
> # Get your website & secret key in your plaza.
> $buckaroo = new \Buckaroo('WEBSITE_KEY', 'SECRET_KEY');

**Comment by abrookbanks** [comment]
That did work but the payment object doesn't exist as per the documentation.

```
require './vendor/autoload.php';
$buckaroo = new Buckaroo\BuckarooClient('xxx', 'yyy');
$payment = $buckaroo->payment('creditcard') ->pay(['name' => 'visa','amountDebit' => 10,'invoice' => 'xxx']);
```

 > Call to undefined method BuckarooBuckarooClient::payment()

**Comment by abrookbanks** [comment]
Thanks. I'll take a look. Critical to get documentation up to date. Thanks guys!! :)

**Comment by abrookbanks** [comment]
It would be far easier from a developers point of view if you could create a checkout session like Stripe to a hosted page to choose payment option. Coding each payment option adds a lot of integration work.

**Comment by ShuCh3n** [comment]
Dear @abrookbanks 

We have updated the documentation on our website. Thanks for mentioning it.

We can create something like that, but it will only work for some of our payments. Payments such as Klarna, Afterpay, Billink, etc. will not work on a hosted payment page. These payments require more data from the merchant in order to work correctly.

**Comment by abrookbanks** [comment]
Just for some constructive feedback there are some huge issues with Buckaroo from a developers point of view. Firstly its not one integration but lots of different ones. Why is gender a required field for Klarna? Why can't Euros be used as a currency for UK customers. Why is house number a required field. I've had to abandon as its horrible to work with. I'm sorry.

**Comment by ShuCh3n** [comment]
Dear @abrookbanks 

Thank you so much for your feedback. We are always open to improving our code. I will do my best to answer all your questions.

- Gender is a required field for Klarna but not for KlarnaKP
- You can use EUR for UK customers. Simply define currency in your payload. (Remember to check if the EUR is enabled for Klarna in your plaza account.)
- Same as gender, it's not required in KlarnaKP, but it's required for Klarna.

The required fields are validated once the call is made, so the API handles it. There isn't a validation for your payload in the SDK. Klarna and KlarnaKP are two different payment methods with dedicated endpoints.

So sorry to hear that you had a horrible experience with our SDK. I'm willing to have a call with you if you are open to it.

Shu

**Comment by abrookbanks** [comment]
Thanks Shu. I get the necessity of multiple integration.

**Comment by Buckaroo-Rens** [comment]
@abrookbanks Is there any way we can help you right now with the issues you've been experiencing? The SDK is still a relatively new product, which fortunately many people already enjoy using.

We would also like to help you to have the same experience.

As indicated, we are open to a (video) call to help you with certain matters and will of course try to process the feedback you have previously given as best as possible.
