### ISSUE TITLE
BP-2404 Support PHP 8.2

### ISSUE THREAD

**Issue by akonjakow** [buckaroo-it/BuckarooSDK_PHP#91]
deprecations 
* Creation of dynamic property Buckaroo\Handlers\Logging\Observers\Monolog::$log is deprecated

* Creation of dynamic property Buckaroo\Transaction\Request\HttpClient\HttpClientGuzzle::$httpClient is deprecated

* Creation of dynamic property Buckaroo\PaymentMethods\PaymentFacade::$client is deprecated

* Creation of dynamic property Buckaroo\PaymentMethods\Bancontact\Bancontact::$serviceCode is deprecated

* Creation of dynamic property Buckaroo\Services\TransactionHeaders\HmacHeader::$hmacGenerator is deprecated

* Creation of dynamic property Buckaroo\Services\TransactionHeaders\CultureHeader::$locale is deprecated

* Creation of dynamic property Buckaroo\Transaction\Response\TransactionResponse::$httpResponse is deprecated

**Comment by Buckaroo-Rens** [comment]
Thanks @akonjakow, we will look into this asap.

**Comment by akonjakow** [comment]
good morning:) Any update on this issue?

**Comment by Buckaroo-Rens** [comment]
@akonjakow Yes, sorry that it's taking longer then expected. We started working on multiple improvements (this is one of them) and suspect it to be finished in the coming days.

**Comment by ShuCh3n** [comment]
See #95

**Comment by akonjakow** [comment]
when do you expect a release?

**Comment by Buckaroo-Rens** [comment]
@akonjakow Early next week at the latest.

**Comment by ShuCh3n** [comment]
Released https://github.com/buckaroo-it/BuckarooSDK_PHP/releases/tag/1.5.0

**Comment by akonjakow** [comment]
:) Thx
