### ISSUE TITLE
page not found 404

### ISSUE THREAD

**Issue by Lefthandmedia** [buckaroo-it/BuckarooSDK_PHP#96]
Op deze pagina https://www.buckaroo.nl/resources/integratie staat onder de kop **_API & SDK: Volledige vrijheid_** een link naar de **PHP SDK** . Wanneer je op die link klikt krijg je een 404.

https://www.buckaroo.nl/umbraco/PHP%20SDK

Lefthandmedia

**Comment by Buckaroo-Rene** [comment]
@Lefthandmedia,
Bedankt voor het melden. Ik heb intern het team die de buckaroo.nl website beheerd op de hoogte gesteld.
Zij gaan dit z.s.m. oplossen.

**Comment by Buckaroo-Rene** [comment]
@Lefthandmedia ,
The issue has been resolved. Thanks again for informing us.
