### ISSUE TITLE
COuld you give an example of passing customparameters in PHP_SDK?

### ISSUE THREAD

**Issue by Lefthandmedia** [buckaroo-it/BuckarooSDK_PHP#99]
I'm trying to pass custom parameters to an Ideal payment. can you add an example for that?

Thank you
Lefthandmedia

**Comment by Buckaroo-Rens** [comment]
@Lefthandmedia everything clear for now or need some additional help?

**Comment by Lefthandmedia** [comment]
yep,
tnx got it to work confused customparameters with additional parameters
